export const categoriasDisponibles = [
  // Originales
  "Electricista",
  "Plomero",
  "Pintor",
  "Carpintero",
  "Cerrajero",
  "Mecánico",
  "Jardinero",
  "Mudanzas",
  "Profesor particular",
  "Diseñador gráfico",
  "Programador",
  "Contador",
  "Fotógrafo",
  "Veterinario",
  "Asistente virtual",
  "Estilista",
  "Tatuador",
  "Marketing",
  "Traductor",
  "Cuidado de niños",
  "Cuidado de adultos mayores",
  "Entrenador personal",
  "Técnico de PC",
  "Desarrollador web",
  "Servicio de limpieza",
  "Chofer privado",
  "Decorador de interiores",
  "Chef personal",
  "Organizador de eventos",
  "Masajista",
  "Fletes",
  "Albañil",
  "Reparaciones en el hogar",
  "Community Manager",
  "Editor de video",
  "Paseador de perros",
  "Atención al cliente",
  "Reparación de celulares",
  "Profesor de música",

  // Nuevas
  "Gomería",
  "Mecánico",
  "Electromecánico",
  "Soldador",
  "Gasista",
  "Herrero",
  "Asistente contable",
  "Psicólogo",
  "Kinesiólogo",
  "Nutricionista",
  "Enfermero",
  "Diseñador UX/UI",
  "Ilustrador",
  "Guionista",
  "Camarógrafo",
  "Gestor de redes",
  "Tester QA",
  "Coach de vida",
  "Terapista ocupacional",
  "Maquillador profesional",
  "Manicurista",
  "Técnico en refrigeración",
  "Montador de muebles",
  "Bartender",
  "Mozos para eventos",
  "DJ para eventos",
  "Instalador de cámaras",
  "Animador infantil",
  "Profesor de yoga",
  "Instructor de manejo",
  "Lavado de autos",
  "Guardería de mascotas",
  "Personal de seguridad",
  "Coach financiero",
  "Redactor de contenidos",
  "Consultor de negocios",
  "Instalador de paneles solares",
  "Reparador de electrodomésticos",
  "Tapicero",
  "Modista",
  "Sastre",
  "Montador de estructuras",
  "Diseñador industrial",
  "Fotógrafo de producto",
  "Traductor jurado",
  "Desarrollador de apps",
  "Gestor de ecommerce",
  "Abogado",
  "Artesano",
  "Consultor ambiental",
  "Encargado de depósito",
  "Camarero",
  "Panadero",
  "Pastelero",
  "Delivery",
  "Personal de limpieza de oficinas",

  "Ingeniero",
  "Médico",
  "Arquitecto",
  "Odontólogo",
  "Salón de fiestas infantiles",
  "Salón de fiestas",
  "Decoraciones para eventos",
  "Instalador de aire acondicionado",
  "Gestor de trámites",
  "Peluquería de mascotas",
  "Cocinero",
  "Ayudante de cocina",
  "Empleada doméstica",
  "Limpieza comercial",

  "Chef",
  "Cursos",
  "Alquiler de quinchos o locales",
  "Publicidad en radios o medios",
];

export const iconosCategoria = {
  // EXISTENTES
  Servicio: require("../../assets/icons/General.jpg"),
  Mecanico: require("../../assets/icons/Mecanico.jpg"),
  "Chef": require("../../assets/icons/chef.jpg"),
  "chef ": require("../../assets/icons/chef.jpg"),
  "Cursos": require("../../assets/icons/cursos.jpg"),
  "Alquiler de quinchos o locales": require("../../assets/icons/alquiler de quinchos.jpg"),
  "alquiler de Quinchos o locales": require("../../assets/icons/alquiler de quinchos.jpg"),
  "Publicidad en radios o medios": require("../../assets/icons/publicidad de radios.jpg"),
  "publicidad de Radios o medios": require("../../assets/icons/publicidad de radios.jpg"),
  Gomeria: require("../../assets/icons/Gomeria.jpg"),
  "Gomería": require("../../assets/icons/Gomeria.jpg"),
  Electromecanico: require("../../assets/icons/Mecanico.jpg"),
  "Electromecánico": require("../../assets/icons/Mecanico.jpg"),
  Electricista: require("../../assets/icons/electricista.jpg"),
  Plomero: require("../../assets/icons/Plomero.jpg"),
  Pintor: require("../../assets/icons/Pintor.jpg"),
  Carpintero: require("../../assets/icons/Carpintero.jpg"),
  Cerrajero: require("../../assets/icons/Cerrajero.jpg"),
  Mecánico: require("../../assets/icons/Mecanico.jpg"),
  Jardinero: require("../../assets/icons/Jardinero.jpg"),
  Mudanzas: require("../../assets/icons/Mudanza.jpg"),
  "Profesor particular": require("../../assets/icons/Profesor.jpg"),
  "Disenador gráfico": require("../../assets/icons/disenador_grafico.jpg"),
  "Diseñador gráfico": require("../../assets/icons/disenador_grafico.jpg"),
  Programador: require("../../assets/icons/Programador.jpg"),
  Contador: require("../../assets/icons/contador.jpg"),
  Fotógrafo: require("../../assets/icons/Fotografo.jpg"),
  Veterinario: require("../../assets/icons/Veterinario.jpg"),
  "Asistente virtual": require("../../assets/icons/Asistente Virrtual.jpg"),
  Estilista: require("../../assets/icons/Estilista.jpg"),
  Tatuador: require("../../assets/icons/Tatuador.jpg"),
  Marketing: require("../../assets/icons/Marketing.jpg"),
  Traductor: require("../../assets/icons/Traductor.jpg"),
  "Cuidado de niños": require("../../assets/icons/cuidador_de_ninos.jpg"),
  "Cuidado de ancianos": require("../../assets/icons/Cuidado de ancianos.jpg"),
  "Cuidado de adultos mayores": require("../../assets/icons/Cuidado de ancianos.jpg"),
  "Entrenador personal": require("../../assets/icons/Entrenador personal.jpg"),
  "Técnico de PC": require("../../assets/icons/Tecnico de PC.jpg"),
  "Desarrollador web": require("../../assets/icons/Desarrollador Web.jpg"),
  "Servicio de limpieza": require("../../assets/icons/Servicio de limpieza.jpg"),
  "Chofer privado": require("../../assets/icons/Chofer Pirvado.jpg"),
  "Decorador de interiores": require("../../assets/icons/Decorador de Interiores.jpg"),
  "Chef personal": require("../../assets/icons/Chef personal.jpg"),
  "Organizador de eventos": require("../../assets/icons/Organizador de eventos.jpg"),
  Masajista: require("../../assets/icons/Masajista.jpg"),
  Fletes: require("../../assets/icons/Fletes.jpg"),
  Albañil: require("../../assets/icons/albanil.jpg"),
  "Reparaciones en el hogar": require("../../assets/icons/Reparaciones del hogar.jpg"),
  "Community Manager": require("../../assets/icons/Comunity manager.jpg"),
  "Editor de video": require("../../assets/icons/editor de videos.jpg"),
  "Paseador de perros": require("../../assets/icons/Paseador de perros.jpg"),
  "Atención al cliente": require("../../assets/icons/Atencion al cliente.jpg"),
  "Reparación de celulares": require("../../assets/icons/Reparacion de celuilares.jpg"),
  "Profesor de música": require("../../assets/icons/Profesor de musica.jpg"),

  Soldador: require("../../assets/icons/Soldador.jpg"),
  Gasista: require("../../assets/icons/Gasista.jpg"),
  Herrero: require("../../assets/icons/Herrero.jpg"),
  "Asistente contable": require("../../assets/icons/Asisrtente Contable.jpg"),
  Psicólogo: require("../../assets/icons/Psicologo.jpg"),
  Kinesiólogo: require("../../assets/icons/Kinesiologo.jpg"),
  Nutricionista: require("../../assets/icons/Nutricionista.jpg"),
  Enfermero: require("../../assets/icons/Enfermero.jpg"),
  "Disenador UX/UI": require("../../assets/icons/disenador_ux.jpg"),
  "Diseñador UX/UI": require("../../assets/icons/disenador_ux.jpg"),
  Ilustrador: require("../../assets/icons/Ilustrador.jpg"),
  Guionista: require("../../assets/icons/Guionista.jpg"),
  Camarógrafo: require("../../assets/icons/Camarografo.jpg"),
 "Gestor de redes": require("../../assets/icons/Gestor de redes.jpg"),
  "Tester QA": require("../../assets/icons/Tester QA.jpg"),
  "Coach de vida": require("../../assets/icons/Coach de vida.jpg"),
  "Terapista ocupacional": require("../../assets/icons/Terapista ocupaciona.jpg"),
  "Maquillador profesional": require("../../assets/icons/Maquillador.jpg"),
  Manicurista: require("../../assets/icons/Manicurista.jpg"),
  "Técnico en refrigeración": require("../../assets/icons/Tecnico en refrigeracion.jpg"),
  "Montador de muebles": require("../../assets/icons/Montador de muebles.jpg"),
  Bartender: require("../../assets/icons/Bartender.jpg"),
  "Mozos para eventos": require("../../assets/icons/Mozo para eventos.jpg"),
  "Dj para eventos": require("../../assets/icons/Dj para eventos.jpg"),
  "DJ para eventos": require("../../assets/icons/Dj para eventos.jpg"),
  "Instalador de cámaras": require("../../assets/icons/Intalador de camaras.jpg"),
  "Animador infantil": require("../../assets/icons/Animador infantil.jpg"),
  "Profesor de yoga": require("../../assets/icons/Profesor de yoga.jpg"),
  "Instructor de manejo": require("../../assets/icons/Instructor de manejo.jpg"),
  "Lavado de autos": require("../../assets/icons/Lavado de autos.jpg"),
  "guarderia de mascotas": require("../../assets/icons/Guarderia de mascotas.jpg"),
  "Guardería de mascotas": require("../../assets/icons/Guarderia de mascotas.jpg"),
  "Personal de seguridad": require("../../assets/icons/Personal de seguridad.jpg"),
  "Coach financiero": require("../../assets/icons/Coach financiero.jpg"),
  "Redactor de contenidos": require("../../assets/icons/Redactor de contenidos.jpg"),
  "Consultor de negocios": require("../../assets/icons/Consultor de negocios.jpg"),
  "Instalador de paneles solares": require("../../assets/icons/Instalador de paneles solares.jpg"),
  "Reparador de electrodomésticos": require("../../assets/icons/Reparador de electrodomesticos.jpg"),
  Tapicero: require("../../assets/icons/Tapicero.jpg"),
  Modista: require("../../assets/icons/Modista.jpg"),
  Sastre: require("../../assets/icons/Sastre.jpg"),
  "Montador de estructuras": require("../../assets/icons/Motador de estructuras.jpg"),
  "Disenador industrial": require("../../assets/icons/disenador_industrial.jpg"),
  "Diseñador industrial": require("../../assets/icons/disenador_industrial.jpg"),
  "Fotógrafo de producto": require("../../assets/icons/Fotografo de productos.jpg"),
  "Traductor jurado": require("../../assets/icons/Traductor de Jurado.jpg"),
  "Desarrollador de apps": require("../../assets/icons/Desarrollador de apps.jpg"),
  "Gestor de ecommerce": require("../../assets/icons/Gestor de ecommerce.jpg"),
  Abogado: require("../../assets/icons/Abogado.jpg"),
  Artesano: require("../../assets/icons/Artesano.jpg"),
  "Consultor ambiental": require("../../assets/icons/Consultor Ambiental.jpg"),
  "Encargado de depósito": require("../../assets/icons/Encargado de deposito.jpg"),
  Camarero: require("../../assets/icons/Camarero.jpg"),
  Panadero: require("../../assets/icons/Panadero.jpg"),
  Pastelero: require("../../assets/icons/Pastelero.jpg"),
  Delivery: require("../../assets/icons/Delivery.jpg"),
  "Personal de limpieza de oficinas": require("../../assets/icons/Personal de limpieza.jpg"),

  Ingeniero: require("../../assets/icons/Ingeniero.jpg"),
  Médico: require("../../assets/icons/Medico.jpg"),
  Arquitecto: require("../../assets/icons/Arquitecto.jpg"),
  Odontólogo: require("../../assets/icons/odontologo.jpg"),
  "Salón de fiestas infantiles": require("../../assets/icons/Salon de fiestas infantiles.jpg"),
  "Salón de fiestas": require("../../assets/icons/Salon de fiestas.jpg"),
  "Decoraciones para eventos": require("../../assets/icons/decoraciones para eventos.jpg"),
  "Instalador de aire acondicionado": require("../../assets/icons/instalador de aires acondicionados.jpg"),
  "Gestor de trámites": require("../../assets/icons/gestor de tramites.jpg"),
  "Peluquería de mascotas": require("../../assets/icons/peluqueria de mascotas.jpg"),
  Cocinero: require("../../assets/icons/cocinero.jpg"),
  "Ayudante de cocina": require("../../assets/icons/ayudante de cocina.jpg"),
  "Empleada doméstica": require("../../assets/icons/empleada domestica.jpg"),
  "Limpieza comercial": require("../../assets/icons/limpieza comercial.jpg"),
};

export const categoriasPorSeccion = {
  Hogar: [
    "Electricista",
    "Gasista",
    "Plomero",
    "Pintor",
    "Carpintero",
    "Cerrajero",
    "Jardinero",
    "Albañil",
    "Tapicero",
    "Reparaciones en el hogar",
    "Servicio de limpieza",
    "Montador de muebles",
    "Decorador de interiores",
    "Técnico en refrigeración",
    "Instalador de aire acondicionado",
    "Reparador de electrodomésticos",
    "Empleada doméstica",
  ],
  Construcción: [
    "Soldador",
    "Herrero",
    "Montador de estructuras",
    "Instalador de paneles solares",
  ],
  "Oficios Generales": [
    "Encargado de depósito",
    "Camarero",
    "Panadero",
    "Pastelero",
    "Personal de limpieza de oficinas",
    "Personal de seguridad",
    "Cocinero",
    "Chef",
    "Ayudante de cocina",
    "Limpieza comercial",
  ],
  Transporte: [
    "Fletes",
    "Mudanzas",
    "Electromecánico",
    "Gomería",
    "Mecánico",
    "Chofer privado",
    "Delivery",
    "Instructor de manejo",
    "Lavado de autos",
  ],
  Tecnología: [
    "Programador",
    "Técnico de PC",
    "Tester QA",
    "Desarrollador web",
    "Desarrollador de apps",
    "Reparación de celulares",
    "Instalador de cámaras",
    "Community Manager",
    "Editor de video",
    "Diseñador UX/UI",
    "Redactor de contenidos",
    "Gestor de ecommerce",
  ],
  Profesionales: [
    "Contador",
    "Asistente contable",
    "Diseñador gráfico",
    "Consultor de negocios",
    "Abogado",
    "Consultor ambiental",
    "Marketing",
    "Gestor de redes",
    "Traductor jurado",
    "Atención al cliente",
    "Asistente virtual",
    "Coach financiero",
    "Coach de vida",
    "Ingeniero",
    "Arquitecto",
    "Médico",
    "Odontólogo",
    "Gestor de trámites",
  ],
  Salud: ["Psicólogo", "Kinesiólogo", "Nutricionista"],
  Cuidados: [
    "Cuidado de niños",
    "Cuidado de adultos mayores",
    "Enfermero",
  ],
  Bienestar: [
    "Entrenador personal",
    "Masajista",
    "Estilista",
    "Maquillador profesional",
    "Tatuador",
    "Manicurista",
    "Terapista ocupacional",
  ],
  Mascotas: [
    "Paseador de perros",
    "Veterinario",
    "Guardería de mascotas",
    "Peluquería de mascotas",
  ],
  Eventos: [
    "Organizador de eventos",
    "Fotógrafo",
    "Fotógrafo de producto",
    "Camarógrafo",
    "Animador infantil",
    "Mozos para eventos",
    "Bartender",
    "DJ para eventos",
    "Chef personal",
    "Salón de fiestas infantiles",
    "Salón de fiestas",
    "Decoraciones para eventos",
    "Alquiler de quinchos o locales",
    "Publicidad en radios o medios",
  ],
  Educación: [
    "Profesor particular",
    "Traductor",
    "Profesor de música",
    "Profesor de yoga",
    "Cursos",
  ],
  "Arte y cultura": [
    "Ilustrador",
    "Guionista",
    "Diseñador industrial",
    "Sastre",
    "Modista",
    "Artesano",
  ],
};



