-- Métricas operativas, reputación verificada y cierre de trabajos.
-- Todos los cambios son aditivos y preservan pagos, chats y perfiles existentes.

create or replace function public.is_operational_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.usuarios
    where id = auth.uid()
      and rol::text = 'admin'
  );
$$;

revoke all on function public.is_operational_admin() from public;
grant execute on function public.is_operational_admin() to authenticated;
grant execute on function public.is_operational_admin() to service_role;

create table if not exists public.marketplace_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null,
  province text,
  city text,
  category text,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint marketplace_events_name_check check (
    event_name ~ '^marketplace_[a-z0-9_]{2,80}$'
  ),
  constraint marketplace_events_context_object_check check (
    jsonb_typeof(context) = 'object'
  )
);

create index if not exists marketplace_events_created_idx
  on public.marketplace_events (created_at desc);

create index if not exists marketplace_events_funnel_idx
  on public.marketplace_events (event_name, created_at desc);

create index if not exists marketplace_events_location_idx
  on public.marketplace_events (province, city, created_at desc);

alter table public.marketplace_events enable row level security;

drop policy if exists marketplace_events_admin_read
  on public.marketplace_events;
create policy marketplace_events_admin_read
  on public.marketplace_events
  for select
  to authenticated
  using (public.is_operational_admin());

grant select on public.marketplace_events to authenticated;
grant all on public.marketplace_events to service_role;

create or replace function public.track_marketplace_event(
  p_event_name text,
  p_context jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_id bigint;
  v_context jsonb := coalesce(p_context, '{}'::jsonb);
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if p_event_name is null
    or p_event_name !~ '^marketplace_[a-z0-9_]{2,80}$'
  then
    raise exception 'INVALID_EVENT_NAME';
  end if;

  if jsonb_typeof(v_context) <> 'object'
    or octet_length(v_context::text) > 4096
  then
    raise exception 'INVALID_EVENT_CONTEXT';
  end if;

  if exists (
    select 1
    from jsonb_object_keys(v_context) as key_name
    where lower(key_name) = any (
      array[
        'email',
        'telefono',
        'phone',
        'celular',
        'dni',
        'direccion',
        'address',
        'mensaje',
        'message',
        'transcript',
        'transcripcion',
        'nombre',
        'name'
      ]
    )
  ) then
    raise exception 'SENSITIVE_EVENT_CONTEXT';
  end if;

  -- Los identificadores internos no son necesarios para medir el embudo.
  v_context := v_context
    - array[
        'chat_id',
        'provider_id',
        'usuario_id',
        'user_id',
        'payment_id',
        'message_id'
      ];

  insert into public.marketplace_events (
    user_id,
    event_name,
    province,
    city,
    category,
    context
  )
  values (
    auth.uid(),
    p_event_name,
    left(nullif(trim(v_context ->> 'provincia'), ''), 120),
    left(nullif(trim(v_context ->> 'ciudad'), ''), 120),
    left(
      nullif(
        trim(coalesce(v_context ->> 'categoria', v_context ->> 'category')),
        ''
      ),
      120
    ),
    v_context
  )
  returning id into v_event_id;

  return v_event_id;
end;
$$;

revoke all on function public.track_marketplace_event(text, jsonb) from public;
grant execute on function public.track_marketplace_event(text, jsonb)
  to authenticated;
grant execute on function public.track_marketplace_event(text, jsonb)
  to service_role;

alter table public.service_confirmation_payments
  add column if not exists job_status text not null default 'pending',
  add column if not exists completed_at timestamptz;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'service_confirmation_payments_job_status_check'
      and conrelid = 'public.service_confirmation_payments'::regclass
  ) then
    alter table public.service_confirmation_payments
      add constraint service_confirmation_payments_job_status_check
      check (
        job_status in (
          'pending',
          'confirmed',
          'completed',
          'disputed',
          'cancelled'
        )
      );
  end if;
end
$$;

update public.service_confirmation_payments
set job_status = 'confirmed'
where status = 'approved'
  and job_status = 'pending';

create index if not exists service_confirmation_payments_job_status_idx
  on public.service_confirmation_payments (job_status, created_at desc);

create table if not exists public.service_job_reviews (
  id uuid primary key default gen_random_uuid(),
  payment_record_id uuid not null unique
    references public.service_confirmation_payments(id) on delete restrict,
  chat_id uuid not null references public.chats(id) on delete restrict,
  reviewer_id uuid not null references auth.users(id) on delete restrict,
  provider_id uuid not null references auth.users(id) on delete restrict,
  rating smallint not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint service_job_reviews_not_self check (reviewer_id <> provider_id),
  constraint service_job_reviews_comment_length check (
    comment is null or char_length(comment) <= 800
  )
);

create index if not exists service_job_reviews_provider_idx
  on public.service_job_reviews (provider_id, created_at desc);

alter table public.service_job_reviews enable row level security;

drop policy if exists service_job_reviews_participants_read
  on public.service_job_reviews;
create policy service_job_reviews_participants_read
  on public.service_job_reviews
  for select
  to authenticated
  using (auth.uid() = reviewer_id or auth.uid() = provider_id);

drop policy if exists service_job_reviews_service_role_all
  on public.service_job_reviews;
create policy service_job_reviews_service_role_all
  on public.service_job_reviews
  for all
  to service_role
  using (true)
  with check (true);

grant select on public.service_job_reviews to authenticated;
grant all on public.service_job_reviews to service_role;

create or replace function public.submit_service_job_review(
  p_payment_record_id uuid,
  p_rating smallint,
  p_comment text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_payment public.service_confirmation_payments%rowtype;
  v_review public.service_job_reviews%rowtype;
  v_comment text := nullif(trim(coalesce(p_comment, '')), '');
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if p_rating is null or p_rating < 1 or p_rating > 5 then
    raise exception 'INVALID_RATING';
  end if;

  if v_comment is not null and char_length(v_comment) > 800 then
    raise exception 'COMMENT_TOO_LONG';
  end if;

  select *
  into v_payment
  from public.service_confirmation_payments
  where id = p_payment_record_id
  for update;

  if not found then
    raise exception 'PAYMENT_NOT_FOUND';
  end if;

  if v_payment.payer_id <> auth.uid() then
    raise exception 'ONLY_PAYER_CAN_REVIEW';
  end if;

  if v_payment.status <> 'approved' then
    raise exception 'JOB_NOT_CONFIRMED';
  end if;

  if v_payment.job_status in ('disputed', 'cancelled') then
    raise exception 'JOB_NOT_REVIEWABLE';
  end if;

  update public.service_confirmation_payments
  set
    job_status = 'completed',
    completed_at = coalesce(completed_at, now())
  where id = v_payment.id;

  insert into public.service_job_reviews (
    payment_record_id,
    chat_id,
    reviewer_id,
    provider_id,
    rating,
    comment
  )
  values (
    v_payment.id,
    v_payment.chat_id,
    auth.uid(),
    v_payment.provider_id,
    p_rating,
    v_comment
  )
  on conflict (payment_record_id)
  do update set
    rating = excluded.rating,
    comment = excluded.comment,
    updated_at = now()
  returning * into v_review;

  return jsonb_build_object(
    'ok', true,
    'review_id', v_review.id,
    'job_status', 'completed',
    'rating', v_review.rating
  );
end;
$$;

revoke all on function public.submit_service_job_review(uuid, smallint, text)
  from public;
grant execute on function public.submit_service_job_review(uuid, smallint, text)
  to authenticated;
grant execute on function public.submit_service_job_review(uuid, smallint, text)
  to service_role;

create or replace function public.get_chat_job_status(p_chat_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select jsonb_build_object(
    'payment_record_id', payment.id,
    'status', payment.status,
    'job_status', payment.job_status,
    'amount_total', payment.amount_total,
    'currency', payment.currency,
    'provider_id', payment.provider_id,
    'payer_id', payment.payer_id,
    'is_payer', payment.payer_id = auth.uid(),
    'can_review',
      payment.payer_id = auth.uid()
      and payment.status = 'approved'
      and payment.job_status = 'confirmed'
      and review.id is null,
    'completed_at', payment.completed_at,
    'rating', review.rating,
    'reviewed_at', review.created_at
  )
  into v_result
  from public.service_confirmation_payments as payment
  left join public.service_job_reviews as review
    on review.payment_record_id = payment.id
  where payment.chat_id = p_chat_id
    and payment.status = 'approved'
    and auth.uid() in (payment.payer_id, payment.provider_id)
  order by payment.approved_at desc nulls last, payment.created_at desc
  limit 1;

  return coalesce(v_result, '{}'::jsonb);
end;
$$;

revoke all on function public.get_chat_job_status(uuid) from public;
grant execute on function public.get_chat_job_status(uuid) to authenticated;
grant execute on function public.get_chat_job_status(uuid) to service_role;

create table if not exists public.provider_chat_response_times (
  id bigint generated by default as identity primary key,
  chat_id uuid not null references public.chats(id) on delete cascade,
  provider_id uuid not null references auth.users(id) on delete cascade,
  requester_id uuid not null references auth.users(id) on delete cascade,
  first_request_at timestamptz not null,
  first_response_at timestamptz not null,
  response_minutes numeric(12, 2) not null check (response_minutes >= 0),
  created_at timestamptz not null default now(),
  constraint provider_chat_response_times_unique unique (chat_id, provider_id),
  constraint provider_chat_response_times_not_self
    check (provider_id <> requester_id)
);

create index if not exists provider_chat_response_times_provider_idx
  on public.provider_chat_response_times (provider_id, first_response_at desc);

alter table public.provider_chat_response_times enable row level security;
revoke all on public.provider_chat_response_times from anon, authenticated;
grant all on public.provider_chat_response_times to service_role;

create or replace function public.capture_provider_first_response()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_requester_id uuid;
  v_first_request_at timestamptz;
  v_response_at timestamptz;
begin
  if new.chat_id is null or new.remitente_id is null then
    return new;
  end if;

  if not exists (
    select 1
    from public.usuarios as usuario
    where usuario.id = new.remitente_id
      and (
        usuario.rol::text = 'worker'
        or exists (
          select 1
          from public.servicios as servicio
          where servicio.user_id = usuario.id
             or servicio.usuario_id = usuario.id
        )
      )
  ) then
    return new;
  end if;

  select
    message.remitente_id,
    coalesce(
      message.created_at,
      message.creado_en,
      message.fecha_creacion,
      now()
    )
  into v_requester_id, v_first_request_at
  from public.mensajes as message
  where message.chat_id = new.chat_id
    and message.remitente_id is not null
    and message.remitente_id <> new.remitente_id
  order by coalesce(
    message.created_at,
    message.creado_en,
    message.fecha_creacion,
    now()
  )
  limit 1;

  if v_requester_id is null or v_first_request_at is null then
    return new;
  end if;

  if not exists (
    select 1
    from auth.users
    where id = v_requester_id
  ) or not exists (
    select 1
    from auth.users
    where id = new.remitente_id
  ) then
    return new;
  end if;

  v_response_at := coalesce(
    new.created_at,
    new.creado_en,
    new.fecha_creacion,
    now()
  );

  if v_response_at < v_first_request_at then
    return new;
  end if;

  insert into public.provider_chat_response_times (
    chat_id,
    provider_id,
    requester_id,
    first_request_at,
    first_response_at,
    response_minutes
  )
  values (
    new.chat_id,
    new.remitente_id,
    v_requester_id,
    v_first_request_at,
    v_response_at,
    extract(epoch from (v_response_at - v_first_request_at)) / 60.0
  )
  on conflict (chat_id, provider_id) do nothing;

  return new;
end;
$$;

drop trigger if exists capture_provider_first_response
  on public.mensajes;
create trigger capture_provider_first_response
after insert on public.mensajes
for each row execute function public.capture_provider_first_response();

-- No se fuerza un backfill sobre chats históricos: algunos registros antiguos
-- pueden tener participantes ya eliminados. La métrica se completa de manera
-- segura a partir de las respuestas nuevas, sin bloquear conversaciones.

create or replace view public.provider_trust_summary as
with provider_ids as (
  select id as provider_id
  from public.usuarios
  where rol::text = 'worker'
),
review_summary as (
  select
    provider_id,
    count(*)::integer as completed_jobs,
    round(avg(rating)::numeric, 2) as average_rating,
    count(*)::integer as review_count
  from public.service_job_reviews
  group by provider_id
),
response_summary as (
  select
    provider_id,
    count(*)::integer as response_sample_size,
    case
      when count(*) >= 3
        then round(avg(response_minutes)::numeric, 0)
      else null
    end as average_response_minutes
  from public.provider_chat_response_times
  where first_response_at >= now() - interval '90 days'
  group by provider_id
)
select
  provider.provider_id,
  coalesce(review.completed_jobs, 0) as completed_jobs,
  review.average_rating,
  coalesce(review.review_count, 0) as review_count,
  response.average_response_minutes,
  coalesce(response.response_sample_size, 0) as response_sample_size
from provider_ids as provider
left join review_summary as review using (provider_id)
left join response_summary as response using (provider_id);

revoke all on public.provider_trust_summary from anon, authenticated;
grant select on public.provider_trust_summary to service_role;
